get artist and title from title if no tag
osdlyrics/osdlyrics pull request #80
Opened 2020-10-02 09:14 UTC by lakedai

supported filename format: %n.%p-%title, %n.%title, %p-%t
remove "Unknown Artist" artist

2020-10-02 11:16 UTC, PedroHLC requested changes
I have a really big problem with the `%p-%t` format: "Title - Live Somewhere" songs...

Could you do it, triggering only when there is no Author (or when it's "Unknown") instead?

2020-10-02 11:16 UTC, PedroHLC commented on readme.md
> +edit src/ol_metadata.c to support title parse
We already have a `README.md`, no need for a second one. Please, merge them...

2020-10-02 11:16 UTC, PedroHLC commented on src/ol_metadata.c
> +  // add lakedai 2020/10/02，parse title to help search
1 - remove your name from this comment, git will remember who did this changes, and you'll be listed as a contributor in the repository;
2 - add to the comment, what are the conditions for this to trigger.

2020-10-02 11:16 UTC, PedroHLC commented on src/ol_metadata.c
> +  // add end
Remove this last comment

2020-10-04 02:19 UTC, lakedai commented
> I have a really big problem with the `%p-%t` format: "Title - Live Somewhere" songs...
> 
> Could you do it, triggering only when there is no Author (or when it's "Unknown") instead?



> I have a really big problem with the `%p-%t` format: "Title - Live Somewhere" songs...
> 
> Could you do it, triggering only when there is no Author (or when it's "Unknown") instead?

ok. your problem is solved in the new commit.
this function is only triggered on search action, both auto and manual.
when tag artist is null, empty, or contains any of the following words, it is considered invalid.
-  "unknown" (case-insensitive) 
-  "未知"
-  “群星"
if tag artist is invalid, artist and title are got from tag title.
whether tag artist is valid or not, track number is always removed from title
when tag title is parsed, the following formats are supported: 
-  %n.%p-%t
-  %n.%t--%p
-  %n.%t
-  %p-%t
-  %t--%p
-  %t

2020-10-05 11:27 UTC, PedroHLC approved these changes
Ok, the changes are nice.
I'll test it and then merge it :smile:

2020-10-07 12:15 UTC, merged

2020-10-07 12:17 UTC, PedroHLC commented
:sweat_smile:  I should have squashed it before :joy: